### ISSUE TITLE
Request to become a co-maintainer for bakery module

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/bakery#1]
Hello @docwilmot and thank you for porting the Bakery module to Backdrop for use in our forum!  Would you be open to me sharing maintainership for Bakery module, at least until we have ironed out all the kinks and have it running on localize.backdropcms.org, api.backdropcms.org and forum.backdropcms.org?

**Comment by docwilmot** [comment]
Of course! This wasnt as much a port as a starting point; I havent tested this at all. So its all yours, anyone.

**Comment by jenlampton** [comment]
It's a great starting point :)

**Comment by jenlampton** [comment]
added myself to readme.
